apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: airnity-test
spec:
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: airnity-test-warehouse
  namespace: airnity-test
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/example/sample-app.git
      branch: main
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: airnity-test
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: airnity-test-warehouse
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: airnity-render
        config:
          environment: dev
          repoURL: https://github.com/example/sample-app.git
          commit: ${{ ctx.promotion.freight.commits[0].id }}
          deployments:
          - clusterId: dev-east
            appName: frontend
          - clusterId: dev-west
            appName: backend
          timeout: 60s
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: airnity-test
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: airnity-test-warehouse
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - uses: airnity-render
        config:
          environment: staging
          repoURL: https://github.com/example/sample-app.git
          commit: ${{ ctx.promotion.freight.commits[0].id }}
          deployments:
          - clusterId: staging-east
            appName: frontend
          - clusterId: staging-west
            appName: backend
          - clusterId: staging-central
            appName: api
          timeout: 60s
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: airnity-test
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: airnity-test-warehouse
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - uses: airnity-render
        config:
          environment: prod
          repoURL: https://github.com/example/sample-app.git
          commit: ${{ ctx.promotion.freight.commits[0].id }}
          deployments:
          - clusterId: prod-east
            appName: frontend
          - clusterId: prod-west
            appName: frontend
          - clusterId: prod-east
            appName: backend
          - clusterId: prod-west
            appName: backend
          - clusterId: prod-central
            appName: api
          timeout: 120s